#!/usr/bin/env python3
"""Write the query language contract table for the reference.

The query engine declares, construct by construct, what it supports in
``cqlhpc/capabilities.py``. This script renders that declaration as a
Markdown table into ``docs/reference/_generated/query_contract.md``, which
``docs/reference/query-language.md`` includes. Run it with the Python
environment of CandyConc whenever the contract changes::

    python docs/_tools/generate_query_contract.py
    python docs/_tools/generate_query_contract.py --check   # exit 1 if the file is out of date

The documentation build itself does not import CandyConc.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent
OUT = DOCS / "reference" / "_generated" / "query_contract.md"


def _find_source() -> None:
    # Prefer the source tree next to the documentation, so that the table
    # describes this checkout and not another installed version.
    for candidate in (DOCS.parent / "app" / "src", DOCS.parent.parent / "app" / "src"):
        if (candidate / "cqlhpc" / "capabilities.py").is_file():
            sys.path.insert(0, str(candidate))
            return
    try:
        import cqlhpc.capabilities  # noqa: F401
    except ImportError:
        raise SystemExit("cqlhpc not found: run from a source checkout or install CandyConc") from None


def _cell(text: str) -> str:
    text = " ".join(str(text).split())
    # House style of the documentation: no semicolons in prose. The contract
    # texts come from the code and are split into sentences here.
    text = re.sub(r";\s*(\S)", lambda m: ". " + m.group(1).upper(), text)
    return text.replace("|", "\\|")


def render() -> str:
    _find_source()
    from cqlhpc import capabilities as caps

    contract = caps.build_cqlf_capability_contract()
    lines = [
        "<!-- Generated by docs/_tools/generate_query_contract.py from cqlhpc/capabilities.py. Do not edit. -->",
        "",
        f"Contract version `{contract['version']}`, declared level `{contract['current_level']}`, "
        f"fingerprint `{str(contract['fingerprint_sha256'])[:12]}`.",
        "",
        "| Construct | Level | Syntax | Execution | Tests | Operators or attributes | Limits and requirements |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for cap in caps.CAPABILITIES:
        ops = list(cap.token_operators) + list(cap.meta_operators) + list(cap.token_attributes)
        ops += list(cap.language_service_attributes)
        ops_text = ", ".join(f"`{_cell(o)}`" for o in ops) if ops else ""
        notes = list(cap.limits) + [f"Requires: {r}" for r in cap.requires]
        lines.append(
            f"| {_cell(cap.title)} (`{cap.id}`) | {cap.level} | {cap.syntax} | {cap.execution} | "
            f"{cap.tests} | {ops_text} | {_cell(' '.join(notes))} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="only compare, do not write")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is out of date. Run docs/_tools/generate_query_contract.py.")
            return 1
        print(f"{OUT} is up to date.")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"written {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
