#!/usr/bin/env python3
"""Write the settings tables of the configuration reference.

The settings, their grouping, and their descriptions are in
``docs/_data/configuration.json``. This script adds the default of every
field of ``AppConfig`` from ``candyconc/config.py`` and checks that every
other listed name is read by the code (or by the launcher of the application
bundle), then writes ``docs/reference/_generated/configuration.md``, which
``docs/reference/configuration.md`` includes. Run it with the Python
environment of CandyConc whenever a setting changes::

    python docs/_tools/generate_configuration.py
    python docs/_tools/generate_configuration.py --check   # exit 1 if the file is out of date

The defaults are the values of an installed package. A source checkout can
add ``[tool.candyconc]`` in ``app/pyproject.toml``, which the generated table
ignores on purpose. The documentation build itself does not import CandyConc.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent
DATA = DOCS / "_data" / "configuration.json"
OUT = DOCS / "reference" / "_generated" / "configuration.md"


def _app_dir() -> Path:
    for candidate in (DOCS.parent / "app", DOCS.parent.parent / "app"):
        if (candidate / "src" / "candyconc" / "config.py").is_file():
            return candidate
    raise SystemExit("app/src/candyconc/config.py not found: run from a source checkout")


def _launcher() -> Path | None:
    for candidate in (DOCS.parent / "packaging", DOCS.parent / "repo_root" / "packaging"):
        path = candidate / "bundle" / "candyconc"
        if path.is_file():
            return path
    return None


def _field_defaults(app: Path) -> dict[str, object]:
    # The pyproject profile of a source checkout must not leak into the table.
    for name in list(os.environ):
        if name.startswith(("CANDYCONC_", "COPILOT_", "LM_STUDIO_")):
            del os.environ[name]
    sys.path.insert(0, str(app / "src"))
    from candyconc.config import AppConfig

    return {name: field.default for name, field in AppConfig.model_fields.items()}


def _source_text(app: Path) -> str:
    parts = []
    for path in sorted((app / "src").rglob("*.py")):
        parts.append(path.read_text(encoding="utf-8", errors="ignore"))
    return "\n".join(parts)


def _default_text(value: object) -> str:
    if value is None or value == "":
        return "not set"
    if isinstance(value, bool):
        return "on" if value else "off"
    if isinstance(value, float) and value.is_integer():
        value = int(value)
    return f"`{value}`"


def _cell(text: str) -> str:
    return " ".join(str(text).split()).replace("|", "\\|")


def render() -> str:
    app = _app_dir()
    data = json.loads(DATA.read_text(encoding="utf-8"))
    defaults = _field_defaults(app)
    source = _source_text(app)
    launcher = _launcher()
    launcher_text = launcher.read_text(encoding="utf-8") if launcher else ""
    problems: list[str] = []
    lines = [
        "<!-- Generated by docs/_tools/generate_configuration.py from docs/_data/configuration.json and candyconc/config.py. Do not edit. -->",
        "",
    ]
    for section in data["sections"]:
        lines += [f"## {section['title']}", ""]
        for group in section["groups"]:
            lines += [f"### {group['title']}", ""]
            if group.get("intro"):
                lines += [group["intro"], ""]
            lines += ["| Setting | Default | Effect |", "| --- | --- | --- |"]
            for setting in group["settings"]:
                name = setting["name"]
                if name in defaults:
                    if "default" in setting:
                        problems.append(f"{name}: an AppConfig field, remove 'default' from configuration.json")
                    default = _default_text(defaults[name])
                else:
                    if "default" not in setting:
                        problems.append(f"{name}: not an AppConfig field, configuration.json needs 'default'")
                    haystack = launcher_text if setting.get("source") == "launcher" else source
                    if not re.search(rf"[\"']{re.escape(name)}[\"']|\b{re.escape(name)}\b", haystack):
                        problems.append(f"{name}: no code reads this name")
                    # Written as displayed in configuration.json.
                    default = setting.get("default") or "not set"
                lines.append(f"| `{name}` | {_cell(default)} | {_cell(setting['text'])} |")
            lines.append("")
    if problems:
        raise SystemExit("\n".join(problems))
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if the generated file is out of date")
    args = ap.parse_args()
    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != text:
            print(f"{OUT} is out of date. Run: python docs/_tools/generate_configuration.py")
            return 1
        print(f"{OUT} is current.")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
