"""The text of a GitHub release and the metadata check of the sdist (packaging/).

The release workflow read ``RELEASE_NOTES.md`` at the repository root, which
the repository does not have, and fell back to notes generated by GitHub. The
maintained notes are ``docs/help/release-notes.md`` (RC0 report, B4).
``packaging/release_notes.py`` writes the release text from that page.
``packaging/check_sdist.py`` finds absolute paths in the sdist metadata
(RC0 report, B2).
"""

from __future__ import annotations

import importlib.util
import io
import re
import sys
import tarfile
from pathlib import Path

import pytest

APP = Path(__file__).resolve().parents[2]


def _packaging_dir() -> Path | None:
    for candidate in (APP.parent / "packaging", APP.parent / "repo_root" / "packaging"):
        if (candidate / "build_web.py").is_file():
            return candidate
    return None


PACKAGING = _packaging_dir()
pytestmark = pytest.mark.skipif(PACKAGING is None, reason="packaging/ is not part of this checkout")


def _load(name: str):
    path = PACKAGING / name
    assert path.is_file(), f"{path} missing"
    spec = importlib.util.spec_from_file_location(f"candyconc_packaging_{path.stem}", path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def notes():
    return _load("release_notes.py")


@pytest.fixture(scope="module")
def check_sdist():
    return _load("check_sdist.py")


def test_release_text_of_the_current_version(notes, tmp_path):
    out = tmp_path / "RELEASE_NOTES.md"
    root = notes.repo_root()
    version = notes.project_table(root)["version"]
    assert notes.main(["--tag", f"v{version}", "--repository-url", "https://github.com/o/r", "--output", str(out)]) == 0
    text = out.read_text(encoding="utf-8")

    assert not text.startswith("## CandyConc")
    assert "<!--" not in text
    assert not re.search(r"^### ", text, re.M)
    assert "## Downloads" in text
    targets = re.findall(r"\]\(([^)]+)\)", text)
    assert targets
    for target in targets:
        assert target.startswith("https://"), target
    base = f"https://github.com/o/r/blob/v{version}/docs/"
    docs = notes.docs_dir(root)
    for target in targets:
        if target.startswith(base):
            assert (docs / target[len(base):].partition("#")[0]).is_file(), target


def test_tag_must_match_the_version(notes):
    with pytest.raises(SystemExit, match="does not match"):
        notes.main(["--tag", "v0.0.0-not-this", "--output", "/dev/null"])


def test_link_to_a_missing_page_stops(notes, tmp_path):
    docs = tmp_path / "docs"
    (docs / "help").mkdir(parents=True)
    text = "## CandyConc 1.0\n\nSee [Install](../get-started/missing.md).\n"
    with pytest.raises(SystemExit, match="no page of the documentation"):
        notes.render(text, "1.0", docs, "https://x/docs/")


def test_links_resolve_relative_to_the_notes_page(notes, tmp_path):
    docs = tmp_path / "docs"
    (docs / "help").mkdir(parents=True)
    (docs / "get-started").mkdir()
    (docs / "get-started" / "install.md").write_text("# Install\n", encoding="utf-8")
    (docs / "help" / "troubleshooting.md").write_text("# Troubleshooting\n", encoding="utf-8")
    text = (
        "<!-- draft -->\n## CandyConc 1.0\n\n### Downloads\n\n"
        "See [Install](../get-started/install.md), [Fix](troubleshooting.md#a-b) and [Web](https://example.org).\n"
        "\n## CandyConc 0.9\n\nOld.\n"
    )
    rendered = notes.render(text, "1.0", docs, "https://x/blob/v1.0/docs/")
    assert rendered == (
        "## Downloads\n\n"
        "See [Install](https://x/blob/v1.0/docs/get-started/install.md), "
        "[Fix](https://x/blob/v1.0/docs/help/troubleshooting.md#a-b) and [Web](https://example.org).\n"
    )


def test_myst_role_stops(notes, tmp_path):
    with pytest.raises(SystemExit, match="MyST role"):
        notes.render("## CandyConc 1.0\n\nSee {doc}`install`.\n", "1.0", tmp_path, "https://x/")


def _sdist(tmp_path: Path, sources: str) -> Path:
    path = tmp_path / "candyconc-1.0.tar.gz"
    with tarfile.open(path, "w:gz") as tar:
        for name, text in (
            ("candyconc-1.0/PKG-INFO", "Name: candyconc\n"),
            ("candyconc-1.0/src/candyconc.egg-info/SOURCES.txt", sources),
        ):
            data = text.encode()
            info = tarfile.TarInfo(name)
            info.size = len(data)
            tar.addfile(info, io.BytesIO(data))
    return path


def test_sdist_check_finds_build_paths(check_sdist, tmp_path):
    sdist = _sdist(tmp_path, "setup.py\n/home/runner/work/app/build/cython/src/candyconc/core/_fast_count.c\n")
    assert check_sdist.main([str(sdist)]) == 1


def test_sdist_check_accepts_relative_sources(check_sdist, tmp_path):
    sdist = _sdist(tmp_path, "setup.py\nsrc/candyconc/core/_fast_count.pyx\n")
    assert check_sdist.main([str(sdist)]) == 0
